{
 "title": "Custom API – Open-Meteo",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(label_values(up, instance))"
    }
   },
   {
    "name": "city",
    "query": {
     "query": "label_values(weather_temperature_c, city)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Target uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"custom_api\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Свежесть данных",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - exporter_last_scrape_ts{city=~\"$city\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average API Latency for 5 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(weather_api_latency_ms{city=~\"$city\"}[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Portion of successful queries in 15 min",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * increase(weather_api_ok_total{city=~\"$city\"}[15m])\n  / (increase(weather_api_ok_total{city=~\"$city\"}[15m]) + increase(weather_api_err_total{city=~\"$city\"}[15m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "error rate in 5 mins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "rate(weather_api_err_total{city=~\"$city\"}[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success rate (req/s, за 5 мин)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "rate(weather_api_ok_total{city=~\"$city\"}[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Humidity in 30 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(weather_humidity_percent{city=~\"$city\"}[30m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity now",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_humidity_percent{city=~\"$city\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MAX wind in 30 min",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(weather_wind_speed{city=~\"$city\"}[30m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind now",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "expr": "weather_wind_speed{city=~\"$city\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Change of temperature in a hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "delta(weather_temperature_c{city=~\"$city\"}[1h])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Temperature for 30 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(weather_temperature_c{city=~\"$city\"}[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature Now",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "weather_temperature_c{city=~\"$city\"}\n\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}