{
 "title": "Database Exporter (PostgreSQL)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "db",
    "query": {
     "query": "label_values(pg_stat_database_xact_commit, datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cache Hit Ratio (%) not correct",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(pg_stat_database_blks_hit{datname=\"$db\"} / (pg_stat_database_blks_hit{datname=\"$db\"} + pg_stat_database_xact_commit{datname=\"$db\"})) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tuples Deleted/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_deleted{datname=\"$db\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tuples Updated/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_updated{datname=\"$db\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tuples Inserted/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{datname=\"$db\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tuples Read/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched{datname=\"$db\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Throughput (QPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "query/sec" } },
   "targets": [
    {
     "expr": "rate(pg_stat_activity_count{datname=\"$db\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions Rolled Back (per sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=\"$db\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Rate (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"$db\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Uptime (hours)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"postgresql\"}) / 3600\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Size ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "pg_database_size_bytes/1024", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_stat_activity_count{datname=\"$db\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}